dist: xenial
language: python
cache: pip
matrix:
  include:
    - name: "3.5"
      python: 3.5
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8-dev"
      python: 3.8-dev
  allow_failures:
    - name: "3.8-dev"
      python: 3.8-dev
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]"
script: pytest --cov=pdutil
after_success:
  - codecov
